name: dbt-singlestore

on: [push]

env:
  LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
  SQL_USER_PASSWORD: ${{ secrets.SQL_USER_PASSWORD }}
  S2MS_API_KEY: ${{ secrets.S2MS_API_KEY }}

jobs:
  fetch-s2-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get_versions.outputs.versions }}
    steps:
      - name: Get supported versions of Singlestore
        id: get_versions
        uses: singlestore-labs/singlestore-supported-versions@main

  build-matrix:
    name: Build test matrix
    runs-on: ubuntu-latest
    needs: fetch-s2-versions
    outputs:
      matrix: ${{ steps.compose.outputs.matrix }}
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Compose matrix JSON
        id: compose
        env:
          VERSIONS: ${{ needs.fetch-s2-versions.outputs.versions }}
        run: |
          base='[{"name":"Managed Service connection test","cluster_type":"s2ms","singlestore_version":"none"}]'

          ciab_rows=$(jq -cn --argjson versions "$VERSIONS" '
            $versions | map({
              name: ("SingleStore " + . + " connection test"),
              cluster_type: "ciab",
              singlestore_version: (.)
            })
          ')

          include=$(jq -cn --argjson base "$base" --argjson extra "$ciab_rows" \
            '{ include: ($base + $extra) }')

          echo "matrix=$include" >> "$GITHUB_OUTPUT"

  test:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    needs: build-matrix
    strategy:
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
      fail-fast: false

    env:
      CLUSTER_TYPE: ${{ matrix.cluster_type }}
      SINGLESTORE_VERSION: ${{ matrix.singlestore_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup build environment
        uses: ./.github/workflows/actions/setup

      - name: Start SingleStore cluster and run integration tests
        run: ./.github/workflows/run-tests.sh


  test-jaffle-shop:
    name: ${{ matrix.name }} - Jaffle Shop
    runs-on: ubuntu-22.04
    needs: build-matrix
    strategy:
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
      fail-fast: false

    env:
      CLUSTER_TYPE: ${{ matrix.cluster_type }}
      SINGLESTORE_VERSION: ${{ matrix.singlestore_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup build environment
        uses: ./.github/workflows/actions/setup

      - name: Run jaffle_shop test
        run: ./.github/workflows/run-jaffle-shop.sh
