name: dbt-singlestore

on: [push]

env:
  LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
  SQL_USER_PASSWORD: ${{ secrets.SQL_USER_PASSWORD }}
  S2MS_API_KEY: ${{ secrets.S2MS_API_KEY }}

jobs:
  test:
    strategy: &dbt_singlestore_strategy
      fail-fast: false
      matrix:
        include:
          - name: "Managed Service connection test"
            cluster_type: s2ms
            ciab_image: none
          - name: "SingleStore 8.5 connection test"
            cluster_type: ciab
            ciab_image: singlestore/cluster-in-a-box:alma-8.5.22-fe61f40cd1-4.1.0-1.17.11
          - name: "SingleStore 8.7 connection test"
            cluster_type: ciab
            ciab_image: singlestore/cluster-in-a-box:alma-8.7.12-483e5f8acb-4.1.0-1.17.15

    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    env:
      CLUSTER_TYPE: ${{ matrix.cluster_type }}
      CIAB_IMAGE: ${{ matrix.ciab_image }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup build environment
        uses: ./.github/workflows/actions/setup

      - name: Start SingleStore cluster and run integration tests
        run: ./.github/workflows/run-tests.sh


  test-jaffle-shop:
    name: ${{ matrix.name }} - Jaffle Shop
    runs-on: ubuntu-22.04

    strategy: *dbt_singlestore_strategy

    env:
      CLUSTER_TYPE: ${{ matrix.cluster_type }}
      CIAB_IMAGE: ${{ matrix.ciab_image }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup build environment
        uses: ./.github/workflows/actions/setup

      - name: Checkout jaffle_shop
        uses: actions/checkout@v3
        with:
          repository: singlestore-labs/jaffle_shop
          path: jaffle_shop

      - name: Run jaffle_shop test
        run: ./.github/workflows/run-jaffle-shop.sh
